<?php

/**
 * @file
 * Install, update and uninstall functions for the paragraphs_pack_node_list module.
 */

/**
 * Implements hook_install().
 */
function paragraphs_pack_node_list_install() {
  paragraphs_pack_create_paragraph(PP_BUNDLE_NODE_LIST, 'Content list');
  paragraphs_pack_add_field_title(PP_BUNDLE_NODE_LIST, 'Title');
  paragraphs_pack_add_field_view_mode(PP_BUNDLE_NODE_LIST, 'View mode');
  paragraphs_pack_add_field_items(PP_BUNDLE_NODE_LIST, 'Items', 'node');
}
